error: Add 2 new error codes
Add 2 new error codes:

 - CERR_PREVIOUS_ERRORS: an object is in an error state due to previous
   uncorrected errors
 - CERR_PARTIAL_FAILURE: an operation that performs multiple independent
   actions had failed only some of them.

Signed-off-by: Alexander Shishkin <alex@ash.works>