error: Add CERR_RET() helper to reduce error checking boilerplate
Currently, as a result of the elaborate error.h infrastructure and its
requirements, there are a lot of instances of

> cerr err = func();
> if (IS_CERR(err))
>     return ...;

which makes things take up more space than necessary and requires typing
out this elaborate construct every time.

Add CERR_RET() macro that does the above in one line like

> CERR_RET(func(), return ...);

Signed-off-by: Alexander Shishkin <alex@ash.works>