error: Move errno_to_cerr() from fs-ops-posix.c
There are more places in the code that want to convert errno values to
cerrs; move errno_to_cerr() from fs-ops-posix.c to error.h and make it a
macro, so that mod:line information reflects the call site.

Signed-off-by: Alexander Shishkin <alex@ash.works>