error: Add CERR_RET helpers for scalar types
Add CERR_RET_SCALAR() and CRES_RET_SCALAR(), which are similar to
CERR_RET_T() and CRES_RET_T(), but for scalar return types.

Signed-off-by: Alexander Shishkin <alex@ash.works>