error: Add CRES_RET() helper to reduce error checking boilerplate
Currently, as a result of the elaborate error.h infrastructure and its
requirements, there are a lot of instances of

> cresp(T) res = func();
> if (IS_CERR(res))
>     return ...;
> ... = res.val;

which makes things take up more space than necessary and requires typing
out this elaborate construct every time.

Add CRES_RET() macro that does the above in one line like

> ... = CRES_RET(func(), return ...);

Signed-off-by: Alexander Shishkin <alex@ash.works>