error: Add reason to cerr/cres
Add a reason substructure to cerr/cres, so that callers can be more
specific about the reason for a particular error; it consists of a
format string and 3 general purpose arguments that can be used with it.

Amend cerr_strbuf() to print the reason if it is provided.

Signed-off-by: Alexander Shishkin <alex@ash.works>